### PR TITLE
colorize output like jq

### PR DESCRIPTION
**Pull request by haraldh**
with colored_json and auto detection, if the output is an ansi terminal

### CODE REVIEW

**Comment by yamafaktory** [comment]
@haraldh Thanks a ton for your contribution 👍.

**Comment by yamafaktory** [comment]
Published https://crates.io/crates/jql/2.1.0 ⚡, thanks again!

**Comment by haraldh** [comment]
Hmm, a lot of your README.md examples don't output valid json..
```
$ cargo run -q --  '"one".[2:0],"two","three"' <<EOF
> {
>   "one": [1, 2, 3],
>   "two": 2,
>   "three": 3
> }
> EOF
Invalid JSON file or content
```

**Comment by yamafaktory** [comment]
@haraldh the latest release should address your issue https://crates.io/crates/jql/2.1.2 🤞.

**Pull request merged**
